### ISSUE TITLE
.onIdentify(identifyHandler) error

### ISSUE THREAD

**Issue by sameeraman** [NabuCasa/home-assistant-google-assistant-local-sdk#1]
I get the following error when I do the inspect on the test receiver. 

![u2wGMeaqqK](https://user-images.githubusercontent.com/18417281/70844609-c64eff80-1e7e-11ea-9083-56a17ffe38fd.png)

And how do we check that it's actually using local calls in this scenario?

**Comment by balloob** [comment]
Are you running this on a Google Home device ?

**Comment by sameeraman** [comment]
No, on the chrome browser for debugging, how do we ensure that google assistant is making local calls?

**Comment by balloob** [comment]
This only works when run on Google Home, as it provides the `cast` object. 

To make sure a command is local, please read the docs https://github.com/NabuCasa/home-assistant-google-assistant-local-sdk/blob/master/REQUEST-RESPONSE.md#execute-intent-received-from-google
