### ISSUE TITLE
local fulfillment broken on 2022.7.ob3

### ISSUE THREAD

**Issue by pdobrien3** [NabuCasa/home-assistant-google-assistant-local-sdk#23]
When going to chrome://inspect/#devices, I can see all my google minis but the inspect link never shows up.

```
Google Home Mini#192.168.1.113
Chromecast Ultra#192.168.1.191
Google Cast Group#192.168.1.198
```
Forcing cloud works, sync works, force local broken

On 2022.7.ob0 I was seeing 404 timeout errors in log explorer when forcing local.

**Comment by Murianwind** [comment]
Me too.. ㅠㅠ

**Comment by balloob** [comment]
Does it work when you roll back to 2022.6?

**Comment by pdobrien3** [comment]
yes, it was working prior to upgrading to the beta.

**Comment by balloob** [comment]
Can you roll back and see if it works again

**Comment by pdobrien3** [comment]
well, not as expected.  Rolling back to 2022.6.7 and still seeing the same behavior.  I am 100% sure it was working before upgrading to the beta though.

**Comment by pdobrien3** [comment]
same behavior on 2022.7.0

**Comment by Murianwind** [comment]
![image](https://user-images.githubusercontent.com/6447460/178093004-1b215fae-6b01-4fd0-85e7-e3062e8d2aba.png)

![image](https://user-images.githubusercontent.com/6447460/178093026-add608dd-8ea6-4c63-a982-9693a3db3878.png)

My guess is that there is nothing wrong with the settings, but when I give voice commands to the Google Home speaker, it doesn't work locally.

![image](https://user-images.githubusercontent.com/6447460/178093078-8b1a8c70-6914-4dd2-a25a-4be986c9d914.png)

**Comment by pdobrien3** [comment]
It’s odd that the inspect link doesn’t even show up for the minis.

**Comment by pdobrien3** [comment]
just a guess but, since the new local sync button is also broken for me, i am guessing it is somehow related to this:

https://github.com/NabuCasa/home-assistant-google-assistant-local-sdk/issues/20

unfortunately, i do not have the knowledge to investigate.

**Comment by pdobrien3** [comment]
is there a debug string i can use to bump the log level up for the google assistant integration?

**Comment by pdobrien3** [comment]
i believe upgrading to the latest beta has fixed several issues.  i can now see my devices in chrome/inspect and local fulfillment works.  the sync devices button in the UI still fails with a 404 error but voice requests to sync devices works.  Was something changed with the google assistant integration in the new beta?

**Comment by balloob** [comment]
no 🤣

**Comment by pdobrien3** [comment]
Ok. Well, absolutely nothing else changed. I have come to the conclusion that local fulfillment is finicky as hell. I have been able to get cloud to perform almost as well as local so 🤷🏼‍♂️  You can close this.
