### ISSUE TITLE
Unable to find HASS connection info.

### ISSUE THREAD

**Issue by Weissnix4711** [NabuCasa/home-assistant-google-assistant-local-sdk#7]
See screenshot.

Same error as #2, but `device[]` array has items in it.

![Screenshot from 2021-01-03 14-33-46](https://user-images.githubusercontent.com/42943391/103481195-2f2e5000-4dd1-11eb-92fc-9d0e9d0615de.png)

I do also notice that `devices[whatev].customData` is empty. Should this be? I thought here should be webhook details for each device? Anyways, uuid and baseUrl are correct in `inputs[0].payload.device.mdnsScanData.txt` and `.data`. Weird. Is this related to the `Unable to find HASS connection info` error?

![Screenshot from 2021-01-03 14-42-43](https://user-images.githubusercontent.com/42943391/103481302-ffcc1300-4dd1-11eb-93b7-395cffd53f52.png)

**Comment by craigcabrey** [comment]
I just ran into this. After digging through source code for a bit, there are two prerequisites for using this: enable the local API & turn off SSL. Once I did that (and ensured that the mDNS response was correct), everything started working.

**Comment by sameeraman** [comment]
@craigcabrey I have this same error. customData is Empty. mDNSScanData is discovered properly. I have turned off SSL. How did you enable local API ?

**Comment by balloob** [comment]
Closing this as this is not an issue related to this JS.
